"""
models/smart_bin.py – Smart Bin Data Models (Pydantic)
Typed models for smart bin monitoring, routing, and optimization.
"""
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class BinCoordinates(BaseModel):
    """Geographic coordinates of a smart bin."""
    lat: float
    lon: float


class OverflowPrediction(BaseModel):
    """AI overflow prediction for a smart bin."""
    hours_until_overflow:  float
    urgent_collection:     bool
    fill_rate_per_day:     float
    prediction_confidence: int = Field(ge=0, le=100)


class BinStatus(BaseModel):
    """Real-time status of a single smart bin."""
    bin_id:             str
    location:           str
    waste_type:         str
    category_color:     str
    fill_level_pct:     float = Field(ge=0, le=100)
    status:             str   # Empty | Partial | High | Overflow
    status_color:       str
    temperature_c:      float
    collection_status:  str
    bin_health:         str   # Good | Warning | Critical
    overflow_prediction: Dict[str, Any]
    coordinates:        Dict[str, float]


class RouteDetails(BaseModel):
    """Details of a single optimized collection route."""
    route_id:              str
    route_name:            str
    bins_assigned:         List[str]
    urgent_bins:           List[str]
    priority:              str   # URGENT | ROUTINE
    distance_km:           float
    collection_schedule:   str
    estimated_time_min:    int


class OptimizationSavings(BaseModel):
    """Savings generated by route optimization."""
    fuel_saved_litres: float
    co2_saved_kg:      float
    time_saved_minutes: float


class RouteOptimization(BaseModel):
    """Full route optimization result."""
    routes:                     List[Dict[str, Any]]
    total_bins_monitored:       int
    total_route_distance_km:    float
    urgent_collections:         int
    optimization_savings:       Dict[str, Any]
    xai_reason:                 str


class SmartBin(BaseModel):
    """Complete smart bin descriptor (used internally for seeding data)."""
    id:       str
    location: str
    type:     str   # waste category key
    lat:      float
    lon:      float


class CollectionSummary(BaseModel):
    """Aggregated smart bin + route summary."""
    smart_bins:         List[Dict[str, Any]]
    route_optimization: Dict[str, Any]
